version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "7080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: utilisateur_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-ressource:
    image: postgres:16
    container_name: postgres-ressource
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: ressource_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_ressource_data:/var/lib/postgresql/data

  postgres-signalement:
    image: postgres:16
    container_name: postgres-signalement
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: signalement_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_signalement_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  utilisateur-service:
    build:
      context: ./utilisateur-service
      dockerfile: Dockerfile
    container_name: utilisateur-service
    depends_on:
      - postgres
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/utilisateur_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "1234"
      KEYCLOAK_SERVER_URL: http://keycloak:8080
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_ADMIN_CLIENT_ID: ${KEYCLOAK_ADMIN_CLIENT_ID}
      KEYCLOAK_ADMIN_CLIENT_SECRET: ${KEYCLOAK_ADMIN_CLIENT_SECRET}
      KEYCLOAK_PUBLIC_CLIENT_ID: ${KEYCLOAK_PUBLIC_CLIENT_ID}
    ports:
      - "7055:7055"
    volumes:
      - utilisateur_logs:/app/logs

  ressource-service:
    build:
      context: ./ressource_service
      dockerfile: Dockerfile
    container_name: ressource-service
    depends_on:
      - postgres-ressource
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-ressource:5432/ressource_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "1234"
      KEYCLOAK_SERVER_URL: http://keycloak:8080
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
    ports:
      - "7056:7056"
    volumes:
      - ressource_logs:/app/logs

  signalement-service:
    build:
      context: ./signalement_service
      dockerfile: Dockerfile
    container_name: signalement-service
    depends_on:
      - postgres-signalement
      - keycloak
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-signalement:5432/signalement_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "1234"
      KEYCLOAK_SERVER_URL: http://keycloak:8080
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "7057:7057"
    volumes:
      - signalement_logs:/app/logs

volumes:
  keycloak_data:
  postgres_data:
  postgres_ressource_data:
  postgres_signalement_data:
  rabbitmq_data:
  utilisateur_logs:
  ressource_logs:
  signalement_logs: