spring.application.name=affectation-service
server.port=7058

spring.datasource.url=jdbc:postgresql://localhost:5436/affectation_db
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
logging.level.org.springframework.security=DEBUG
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:7080/realms/wilaya-interventions
spring.security.oauth2.resourceserver.jwt.audiences=account
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

ressource-service.url=http://localhost:7056

rabbitmq.exchange.affectation=affectation.exchange
rabbitmq.routingkey.equipe-affectee=equipe.affectee

rabbitmq.exchange.notification=notification.exchange
rabbitmq.routing-key.notification=notification.nouvelle-affectation

# Doit correspondre exactement a RabbitMQConfig.QUEUE_CLASSIFIE cote signalement-service
rabbitmq.queue.signalement-classifie=signalements.classifie.queue

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=2000
spring.rabbitmq.listener.simple.default-requeue-rejected=false

logging.level.org.springframework.web=DEBUG
logging.level.com.wilaya=DEBUG