spring.datasource.url=jdbc:h2:mem:affectation_test_db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.auto-startup=false

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:7080/realms/wilaya-interventions

ressource-service.url=http://localhost:7056



































































