spring.application.name=utilisateur-service
server.port=7055
spring.datasource.url=jdbc:postgresql://localhost:5433/utilisateur_db
spring.datasource.username=postgres
spring.datasource.password=1234
logging.level.org.springframework.security=DEBUG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:7080/realms/wilaya-interventions

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=douaemahmoudi66@gmail.com
spring.mail.password=zfgrrdcitibwzhgm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

keycloak.server-url=http://localhost:7080
keycloak.realm=wilaya-interventions
keycloak.admin-client-id=backend-admin-client
keycloak.admin-client-secret=trR63TDkfIozQSS6KOrWgUdD5swTjKDN
keycloak.public-client-id=frontend-app

rabbitmq.exchange.notification=notification.exchange
rabbitmq.routing-key.notification=notification.nouvelle-affectation
rabbitmq.queue.notification=notifications.utilisateur.queue

notification.email.destinataire.test=douaemahmoudi66@gmail.com